name: Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
            echo "GITHUB_REF: ${GITHUB_REF}"
            if [[ "${GITHUB_REF}" =~ ^refs/heads/release/ ]]; then
            VERSION=${GITHUB_REF#refs/heads/release/}
            echo "::set-output name=VERSION::${VERSION}"
            else
            echo "::set-output name=VERSION::unknown"
            fi


      - name: Check version
        run: |
          if [[ "${{ steps.get_version.outputs.VERSION }}" == "unknown" ]]; then
            echo "Error: Version is unknown"
            exit 1
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false