name: Merge dev to release branch

on:
  pull_request:
    types: [opened]
    branches:
      - 'release/*'
    paths-ignore:
      - '**'
jobs:
  check-vercel-deployments:
    if: github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for Vercel
        id: wait-vercel
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          checkName: 'Vercel'
          timeoutSeconds: 600
          intervalSeconds: 10

      - name: Merge PR
        if: steps.wait-vercel.outputs.conclusion == 'success'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}