name: Merge dev to release branch

on:
  pull_request:
    types: [opened]
    branches:
      - 'release/*'

jobs:
  check-vercel-deployments:
    if: github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log deployments
        run: |
          DEPLOYMENTS_URL="https://api.github.com/repos/${{ github.repository }}/deployments?environment=${{ github.event.pull_request.head.ref }}"
          DEPLOYMENTS_JSON=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header "Accept: application/vnd.github.v3+json" $DEPLOYMENTS_URL)
          echo "Deployments JSON: $DEPLOYMENTS_JSON"
          DEPLOYMENT_IDS=$(echo $DEPLOYMENTS_JSON | jq -r '.[].id')
          echo "Deployment IDs: $DEPLOYMENT_IDS"

      - name: Wait for Vercel deployment
        run: |
          VERCEL_DEPLOYMENT_URL="https://api.vercel.com/v5/now/deployments/${{ steps.log-deployments.outputs.deployment_id }}"
          echo "Deplymnet URL: $VERCEL_DEPLOYMENT_URL"
          while true; do
            DEPLOYMENT_STATE=$(curl --header "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" $VERCEL_DEPLOYMENT_URL | jq -r '.state')
            if [ "$DEPLOYMENT_STATE" == "READY" ]; then
              break
            fi
            echo "Waiting for deployment to be ready..."
            sleep 10
          done

      - name: Merge PR
        if: steps.wait-vercel.outputs.conclusion == 'success'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}