name: Merge dev to release branch

on:
  pull_request:
    types: [opened]
    branches:
      - 'release/*'

jobs:
  check-vercel-deployments:
    if: github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log check names
        run: |
          CHECKS_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/checks"
          CHECKS_JSON=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $CHECKS_URL)
          CHECK_NAMES=$(echo $CHECKS_JSON | jq -r '.check_runs[].name')
          echo "Check names: $CHECK_NAMES"

      - name: Wait for Vercel
        id: wait-vercel
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          checkName: 'Vercel'
          timeoutSeconds: 600
          intervalSeconds: 10

      - name: Merge PR
        if: steps.wait-vercel.outputs.conclusion == 'success'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}